// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OrderProducer.OrderKafkaAvro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class OrderKafka : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""OrderKafka"",""namespace"":""OrderProducer.OrderKafkaAvro"",""fields"":[{""name"":""OrderId"",""type"":""string""},{""name"":""CustomerName"",""type"":""string""},{""name"":""Items"",""type"":{""type"":""array"",""items"":""string""}},{""name"":""TotalAmount"",""type"":""double""},{""name"":""ReceivedTimestamp"",""default"":null,""type"":[""null"",""string""]}]}");
		private string _OrderId;
		private string _CustomerName;
		private IList<System.String> _Items;
		private double _TotalAmount;
		private string _ReceivedTimestamp;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return OrderKafka._SCHEMA;
			}
		}
		public string OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				this._CustomerName = value;
			}
		}
		public IList<System.String> Items
		{
			get
			{
				return this._Items;
			}
			set
			{
				this._Items = value;
			}
		}
		public double TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				this._TotalAmount = value;
			}
		}
		public string ReceivedTimestamp
		{
			get
			{
				return this._ReceivedTimestamp;
			}
			set
			{
				this._ReceivedTimestamp = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.OrderId;
			case 1: return this.CustomerName;
			case 2: return this.Items;
			case 3: return this.TotalAmount;
			case 4: return this.ReceivedTimestamp;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.OrderId = (System.String)fieldValue; break;
			case 1: this.CustomerName = (System.String)fieldValue; break;
			case 2: this.Items = (IList<System.String>)fieldValue; break;
			case 3: this.TotalAmount = (System.Double)fieldValue; break;
			case 4: this.ReceivedTimestamp = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
